### ISSUE TITLE
Selection amount issue

### ISSUE THREAD

**Issue by jwinzeler** [jwinzeler/better-battlescribe-exports#26]
The devilfish in the T'au 1000 list has 
![image](https://github.com/jwinzeler/better-battlescribe-exports/assets/37178713/8b667643-3aca-4c0a-9921-b13d7cb392ae)
instead of
![image](https://github.com/jwinzeler/better-battlescribe-exports/assets/37178713/01535244-6e26-4f2c-88fb-0baa41354e0b)

**Comment by littlebigjuko** [comment]
will be fixed in 27-missing-selections
